# greetingcardcapture.com Circle CI
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/
    steps:
      - run:
          name: Install python packages
          command: sudo pip install s3cmd awscli
      - run:
          name: Clone repo
          command: git clone https://github.com/jesselumarie/greetingcardcapture.com.git
      - run:
          name: Write access keys
          command: echo -e "[default] \naccess_key = $S3CFG_ACCESS_KEY \nsecret_key = $S3CFG_SECRET_KEY \n" > $HOME/.s3cfg
      - run:
          name: Push out new code
          command: |
            cd greetingcardcapture.com
            aws s3 sync src/ s3://greetingcardcapture.com --delete
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_ID --paths '/*'

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
